options:
  debug:
    default: "false"
    type: string
    description: Enable verbose logging
  verbose:
    default: "false"
    type: string
    description: Enable debug logging
  config-file:
    default: "/etc/keystone/keystone.conf"
    type: string
    description: Location of keystone configuration file
  service-port:
    default: 5000
    type: int
    description: Port the bind the API server to
  admin-port:
    default: 35357
    type: int
    description: Port the bind the Admin API server to
  keystone-admin-role:
    default: "Admin"
    type: string
    description: "Role that allows admin operations (access to all operations)"
  keystone-service-admin-role:
    default: "KeystoneServiceAdmin"
    type: string
    description: "Role that allows acting as service admin"
  admin-user:
    default: admin
    type: string
    description: Default admin user to create and manage
  token-expiry:
    default: "2017-02-05T00:00"
    type: string
    description: Expiration date of generated admin tokens
  # Database settings used to request access via shared-db-relation-* relations
  database:
    default: "keystone"
    type: string
    description: Database name
  database-user:
    default: "keystone"
    type: string
    description: Database username
