options:
  debug:
    default: "false"
    type: string
    description: "Enable verbose logging"
  verbose:
    default: "false"
    type: string
    description: "Enable debug logging"
  openstack-origin:
    default: distro
    type: "string"
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  config-file:
    default: "/etc/keystone/keystone.conf"
    type: string
    description: "Location of keystone configuration file"
  service-port:
    default: 5000
    type: int
    description: "Port the bind the API server to"
  admin-port:
    default: 35357
    type: int
    description: "Port the bind the Admin API server to"
  keystone-admin-role:
    default: "Admin"
    type: string
    description: "Role that allows admin operations (access to all operations)"
  keystone-service-admin-role:
    default: "KeystoneServiceAdmin"
    type: string
    description: "Role that allows acting as service admin"
  admin-user:
    default: admin
    type: string
    description: "Default admin user to create and manage"
  admin-password:
    default: None
    type: string
    description: "Admin password.  To be used *for testing only*.  Randomly generated by default."
  admin-token:
    default: None
    type: string
    description: "Admin token.  If set, this token will be used for all services instead of being generated per service."
  admin-role:
    default: 'Admin'
    type: string
    description: 'Admin role to be associated with admin and service users'
  token-expiry:
    default: "2017-02-05T00:00"
    type: string
    description: "Expiration date of generated admin tokens"
  service-tenant:
    default: "services"
    type: string
    description: "Name of tenant to associate service credentials."
  # Database settings used to request access via shared-db-relation-* relations
  database:
    default: "keystone"
    type: string
    description: "Database name"
  database-user:
    default: "keystone"
    type: string
    description: "Database username"
  # HA configuration settings
  vip:
    type: string
    description: "Virtual IP to use to front keystone in ha configuration"
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5406
    description: |
      Default multicast port number that will be used to communicate between
      HA Cluster nodes.
